package CourseRegisterUI.models;

public enum College {
    COLLEGE_OF_BIOMEDICINE,
    COLLEGE_OF_BUSINESS,
    COLLEGE_OF_COMPUTING,
    COLLEGE_OF_ENGINEERING,
    COLLEGE_OF_LIBERAL_ARTS,
    COLLEGE_OF_LIFE_SCIENCES,
    SCHOOL_OF_CREATIVE_MEDIA,
    SCHOOL_OF_DATA_SCIENCE,
    SCHOOL_OF_ENERGY_AND_ENVIRONMENT,
    SCHOOL_OF_LAW,
    SCHOOL_OF_GRADUATE_STUDIES,
}
